#!/bin/bash

if true ; then
	cat <<- EOF > /etc/logrotate.d/freepbx-xmpp
	/var/log/asterisk/xmpp_*.log {
		size 50M
		missingok
		dateext
		rotate 5
		notifempty
		sharedscripts
		create 0640 asterisk asterisk
		postrotate
			/usr/sbin/fwconsole pm2 --reload-logs -q
		endscript
	}
	EOF
fi
